name: Install

on:
  push:
  pull_request:

jobs:
  install:
    runs-on: ubuntu-latest

    container: ubuntu:20.04

    steps:
      - name: Install prerequisites
        run: |
          apt update --quiet --quiet
          apt install --no-install-recommends --quiet --yes \
                  patch \
                  sudo

          DEBIAN_FRONTEND=noninteractive \
          apt install --no-install-recommends --quiet --yes \
                  tzdata
      - uses: actions/checkout@v2
      - name: install
        run: |
          ./install.sh
