name: Install

on:
  push:
  pull_request:

jobs:
  install:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: |
          ./install.sh
      - name: setup
        run: |
          ./setup.sh
