name: Install

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: install
        run: |
          docker build .
